### PR TITLE
Ultraweak DPG Poisson Model Problem based on `next`

### PR DESCRIPTION
**Pull request by ac1512**
UW Poisson on top of the next branch (As the previous pull request was on master).

### CODE REVIEW

**Comment by stefanhenneking** [comment]
@ac1512 does this mean we can close the previous PR #127 ?

**Comment by ac1512** [comment]
Yes, we can close the previous PR #127.

**Comment by jbadger95** [comment]
This is a lot to review; I scrolled through it briefly and don't see any glaring issues. Because this is an application and doesn't touch `src` I'm fine pushing it without a detailed review but I can give it a closer look if you wish.

**Comment by jbadger95** [comment]
Nice job BTW Ankit, it looks good!

**Comment by stefanhenneking** [comment]
@jbadger95 thanks for taking a look; I agree, no need to thoroughly review at this point. Before I merge, @ac1512 did you this with MPI, OpenMP, and MPI+OpenMP parallelization?

**Comment by ac1512** [comment]
I have tested this with MPI + OPENMP and MPI.

**Comment by stefanhenneking** [comment]
Closing this PR in favor of #127 which is now easier to merge into `master` after squash-merging `next` in #110

**Pull request closed without merging**
