### PR TITLE
Ultraweak Maxwell problem

### PR DESCRIPTION
**Pull request by jbadger95**
Cleaned up ultraweak Maxwell problem (somewhat, it's honestly still pretty gnarly)

### CODE REVIEW

**Comment by jbadger95** [comment]
@ac1512, @stefanhenneking; This compiles and the small default problem I've set up works (I haven't tested with OMP yet though). I think it's pretty close if either of you have time to work on it / test it.

**Comment by ac1512** [comment]
I can test it tomorrow and let you all know.

**Comment by stefanhenneking** [comment]
@ac1512 Did you review and test this branch?

**Comment by ac1512** [comment]
I have tested this branch on my local machine for the point source and polynomial solution for the Maxwell problem using MPI+OpenMP and it works fine.

**Review by stefanhenneking — APPROVED** [review]
LGTM -- thanks, @jbadger95 !!

**Pull request merged**
